# https://github.com/dart-lang/lints#migrating-from-packagepedantic
include: package:lints/recommended.yaml

analyzer:
  exclude:
    - example/**/*.dart

linter:
  rules:
    - public_member_api_docs